### PR TITLE
Doc: remove beta note from the main doc page

### LINKED ISSUE #687: Remove beta note from documentation
Ahead of the full release, remove the note that PyACP is in beta from the docs.

### PR DESCRIPTION
**Pull request by greschd**
Remove the note that PyACP is in beta from the main documentation page.

Switch the trove classifier to indicate that PyACP is stable.

Closes #687.

### CODE REVIEW

**Comment by greschd** [comment]
We may want to wait with merging this until shortly before release.

**Comment by greschd** [comment]
> We may want to wait with merging this until shortly before release.

Since we're about to publish a release candidate, I think it's ok to remove now.

**Review by roosre — APPROVED** [review]
What do you think about adding a compatibility section like the one at the bottom of this page in [DPF Composites](https://composites.dpf.docs.pyansys.com/version/stable/intro.html)? Or at least a section which informs the customers that 2025 R1 is needed to run all features. I couldn't find any reference to minimum version of the unified installer.

**Comment by roosre** [comment]
I would add a section `Compatibility` under [user guide](https://acp.docs.pyansys.com/version/dev/user_guide/index.html).
I am not sure if we have to list all the details there but at least guide the user to where the information is available (API documentation).

There are quite many API changes: removal of ACPWorkflow, renamings, clean up of the module structure, etc. Depending on the changes, we can provide all details or list the most important changes only.

**Pull request merged**
