### PR TITLE
Add type information to create_ and add_ method documentation

### LINKED ISSUE #612: Type information is not shown in `create_` method documentation
### Description of the modifications

For example the `create_material` documentation https://acp.docs.pyansys.com/version/dev/api/_autosummary/ansys.acp.core.Model.create_material.html does not contain type information, whereas it's present in https://acp.docs.pyansys.com/version/dev/api/_autosummary/ansys.acp.core.Material.html#ansys.acp.core.Material

Either find a way to add it, or link to the instantiated object documentation.

### Useful links and references

_No response_

### PR DESCRIPTION
**Pull request by greschd**
Provide type information for the parameters of the ``create_*`` and ``add_*`` methods in the documentation.

The ``__signature__`` of the methods is constructed from from the wrapped class's signature, only adding a 'self' parameter.

For the ``add_*`` methods, the `Parameters` block (and everything below it) is now also obtained from the class if present.

The 'sphinx-autodoc-typehints' extension previously used does not support showing this dynamically created signature, so it was replaced by using the built-in type hint support of 'sphinx.ext.autodoc'. The only drawback is that defaults are now shown only in the signature, and no longer in the description.

Since 'sphinx.ext.autodoc' however overwrites the class _parameter_ type hints with the class _attribute_ type hints, the helper function used to generate the signature is monkeypatched.

Closes #612

### CODE REVIEW

**Comment by greschd** [comment]
Screenshots: 

### new

image
image

### old
image
image

**Comment by greschd** [comment]
I don't know why `name` is now suddenly shown as `ReadWriteProperty[str, str]` in the main class documentation; that needs fixing.

**Comment by greschd** [comment]
> EDIT: This is a Sphinx bug, see https://github.com/sphinx-doc/sphinx/issues/11207. Probably worth investigating if this can be easily fixed upstream.

For now, I have added a monkeypatch that simply uses the builtin `inspect.signature`.

**Review by roosre — APPROVED** [review]

**Comment by greschd** [comment]
Marked as draft because there is an issue with `intersphinx` that I'll need to investigate - see the failing doc build.

**Pull request merged**
